[build]
  command = "yarn rw deploy netlify"
  publish = "web/dist"
  functions = "api/dist/functions"

[dev]
  # To use [Netlify Dev](https://www.netlify.com/products/dev/),
  # install netlify-cli from https://docs.netlify.com/cli/get-started/#installation
  # and then use netlify link https://docs.netlify.com/cli/get-started/#link-and-unlink-sites
  # to connect your local project to a site already on Netlify
  # then run netlify dev and our app will be accessible on the port specified below
  framework = "redwoodjs"
  # Set targetPort to the [web] side port as defined in redwood.toml
  targetPort = 8910
  # Point your browser to this port to access your RedwoodJS app
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200

[functions]
  included_files = ["api/dist/**/*", "./api/dist/**/*"]
  external_node_modules = ["@babel/runtime-corejs3", "@redwoodjs/auth-clerk-api", "@redwoodjs/api", "inngest", "@redwoodjs/graphql-server", "crypto-js"]

[[plugins]]
  package = "netlify-plugin-inngest"
